// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zjItejrPIvd2Ly69me7-K3_viYXKdAk',
    appId: '1:553776398633:web:0a5a27c6a4583a10cef738',
    messagingSenderId: '553776398633',
    projectId: 'ocean-talk',
    authDomain: 'ocean-talk.firebaseapp.com',
    storageBucket: 'ocean-talk.appspot.com',
    measurementId: 'G-MVYT2H3QGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxAtvgDB0vHFLCluFcTb7W3REedpEvLI',
    appId: '1:553776398633:android:355c653d23b29704cef738',
    messagingSenderId: '553776398633',
    projectId: 'ocean-talk',
    storageBucket: 'ocean-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt--TJD8YXU0KWfnrMIXWcceDgW-L0Xyg',
    appId: '1:553776398633:ios:2be8a74bb356c9aecef738',
    messagingSenderId: '553776398633',
    projectId: 'ocean-talk',
    storageBucket: 'ocean-talk.appspot.com',
    iosBundleId: 'com.example.oceanTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt--TJD8YXU0KWfnrMIXWcceDgW-L0Xyg',
    appId: '1:553776398633:ios:2be8a74bb356c9aecef738',
    messagingSenderId: '553776398633',
    projectId: 'ocean-talk',
    storageBucket: 'ocean-talk.appspot.com',
    iosBundleId: 'com.example.oceanTalk',
  );
}
